### ISSUE TITLE
ns.cmake.install insatll directory for ns.cmake

### ISSUE THREAD

**Issue by jfalcou** [NumScale/ns.cmake#7]
Shoudln't

    set(_PROJECT_DIR           ${NS_CMAKE_EXTERNAL_PROJECTS_DESTINATION})

be

    set(_PROJECT_DIR           ${NS_CMAKE_INSTALL_DIR})

If not, the cmake folder ends up in the binary folder instead

**Comment by ccharly** [comment]
Yes, you're right, thanks! :)
